### ISSUE TITLE
Capture failed

### ISSUE THREAD

**Issue by faultylee** [jpbarraca/LogicAlNucleo#2]
Hi, @jpbarraca nice work on making the NucleoF401RE more useful :)

I'm having trouble with the capture on LogicSniffer and keep getting "Capture Failed". When I looked at your code, it seems that there's no function to return the captured value from inside Sampler.cpp. I later found this 
```
        case SUMP_ARM: {
            sampler.start();
            break;
``` 
and changed `sampler.start()` to `sampler.arm()`, got it working once, but after that it failed to capture again. The board appears hung after I start capture. If I stop the capture and click Show Device matedata, it will fail. Using console showing that the board is not replying at all. Any idea where to look?

**Comment by jpbarraca** [comment]
Can you provide the exact setup and steps so that I can diagnose the problem?
With your change there is the possibility that the code is waiting for a trigger (which doesn't happen) and will stay there forever.

The Nucleo is not that powerful and while it is capturing nothing else is done. Otherwise the timings will be really messed up.

**Comment by faultylee** [comment]
I'm quite new to nucleo, I'm an advance PIC user and Arduino intermediate. Since I've not setup tools to compile the code locally, I copy your code from src and compile using mbed online, then drop the .bin file into the nucleo board. Logic Sniffer is the latest version, ols-0.9.7 SP2. I'm running update to date Arch Linux x64 with the board connected via USB and default to cdc_acm driver.

Btw, I don't find any place that calls `sampler.arm()`

**Comment by faultylee** [comment]
Btw, I've updated the STLink firmware to `V2.J24.M11`, before the update, I can't even see any message from the UART output.

**Comment by jpbarraca** [comment]
I think you are correct. I will check this tonight. Thanks.

**Comment by faultylee** [comment]
Thank you @jpbarraca

**Comment by jpbarraca** [comment]
The code is very simple and is not using interrupts, its all synchronous. Therefore, if the capture process is waiting for completion (e.g., trigger is not matched) it will stay that way until a reset. Sorry, but the board is not that capable.... It barely reaches 10MSPS. I had a different method using interrupt handlers, which did not had this problem, however the capture speed was much much slower. My approach was to maximize speed knowing that, sometimes, I had to push the reset button.

**Comment by faultylee** [comment]
No worries about it, I wasn't needing high sample rate anyway, just wanted to use it to debug some uart issue for my esp8622. 

Maybe a brief mention of the known issue regarding reset might be helpful for any unsuspecting newbies like me, hehe.

Thanks again for the code update. I'll try it out tomorrow.

**Comment by jpbarraca** [comment]
I will add a note.

**Comment by faultylee** [comment]
The updated code is working. Capturing works as expected. Only now I realized the capture hang when I plug in my ESP8266, seems like the 3.3V rail is not sourcing enough current. Thanks again.

**Comment by jpbarraca** [comment]
It could be the case... This is an hack, not a generic solution to reuse boards I had around. I strongly recommend buying a real logical analyser. Even the cheapest ones (~8e) available are enough for those things.

**Comment by faultylee** [comment]
Noted, thanks.
