### ISSUE TITLE
Why aren't you using DMA and timer for acquisition and instead timing by using nop?!

### ISSUE THREAD

**Issue by trollcop** [jpbarraca/LogicAlNucleo#4]
I got linked this by someone looking at F401RE-NUCLEO

I knew this was going to be a mess when files were ending with .cpp, but I was not prepared for the mess that I saw inside sampler.cpp.

Did you know pretty much every STM32 has GPIO DMA which can be triggered from a timer? You setup GPIOx->IDR as src, whatever memory buffer as dst, and each timer tick would transfer the data. With ACCURATE timing.

**Comment by jpbarraca** [comment]
Sure I do :) But I also have access to actual logical analyzers, and this just evolved from a hack.
